### ISSUE TITLE
Multiple issues and suggestions

### ISSUE THREAD

**Issue by amartyarej** [AlecAivazis/feynman#31]
## 1.            "Electroweak" and "gluon" issues
- a)

"Electroweak" and "gluon" are resulting in different end points in the co-ordinate than typed and expected in the code. The PNG works fine in this respect. For example the following code:
`\gluon[color=000000, endcaps=false, flip=false, label=, labelDistance=0.42, labelLocation=0.50, showArrow=true, lineWidth=0.7142857142857143]{1, 3}{1.5, 2}`
It should give a gluon from the co-ordinates (1,3) to (1.5,2). But instead this gives a gluon from (1,3) to (0,3.5)
I think I figured out the mistake in the script.
`$x_{end}^{resulted} = x_{start} + (y_{end}^{expected} - y_{start})$`
 and similarly for y
`$y_{end}^{resulted} = y_{start} + (x_{end}^{expected} - x_{start})$`
The difference in x and y got interchanged in your script.Simply you just have to correct it by adding the difference with the correct variable.
- b)

Electroweak and gluon can have another variable for drawing, which is the **_width of their shape_**, not just the linewidth.
## 2.         Zooming Issues

When exporting to PNG the image outline depends on the zoom scale. **_Also there is no scale to measure the zoom scale_**. By varying the grid and the scroll together can create similar looking space for drawing. 
So here are my suggestions:
- Add a scroll for zooming
- Let us use a simple selector using drag to select the items in a specified region. 
- Create an image of 100% scale for the selected region.
- Using the selector let us change the scale of the specified items altogether.
- When exporting to LaTeX, export the information at 100% zoom scale.
## 3.          Math environment support issue

The text or label is a Math supported text format. It works fine during drawing and in PNG export. But when exported to use in LaTeX, it does not support the Math environment. It is taking too long to run, could not wait for any error messages. For example using `label=$\gamma$` it does not work, but instead using `label=$t$` it gives a non-italic "t".
## 5.          Enable saving the drawing and history

so that reloading the page cannot kill all the time spent for the drawing.

**Comment by AlecAivazis** [comment]
Hey @amartyarej thanks for the suggestions and kind words. 

Unfortunately, I have not been able to do a lot of debugging on the latex package since graduating. I'm sorry for any issues it has caused. I'll try to get something published with the fix soon but have been swamped at work while we try to push for a demo so it might take me a bit. That being said, If you have the time, I would really appreciate a PR with the fixes you mentioned (assuming 1 and 3 are both referring to that). 

Replies to other points:

1.5) For the width of the shape, are you referring to the size of the individual loops? I played around with this awhile ago and ran into some issues but I will try to give it another shot (will make a new issue if its not there).

2) Adding a scroll bar for zoom is a great idea and shouldn't be that hard. The selection for exporting to PNG will probably take me a bit. TBH every time i go into the codebase, I get this really overwhelming urge to rewrite it (I have learned A LOT since i first put this together) so I think this will probably come with that.

4) I think this means you're on a linux machine right? If it just moves the window around then this is a conflict with a system default. The best solution is definitely to change that to something that doesn't conflict but if you dont mind disabling the feature you can do it with this bash command: ```gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier "<Super>"```

5) This is another great idea and I will add this at the top of my list for the rewrite.

**Comment by amartyarej** [comment]
@AlecAivazis  Thanks for your replies.
- 1.a) & 3)
- 
 I think the bug is in the .sty file. I do not have experience with .sty, but I will try and then open the PR. 

- 1.b)
-
Yes I meant the size of the loops in gluon or the amplitude in case of electroweak. Also you can let the user edit the loop number.

- 2)
-
I also meant the exporting to latex at a specified scale.

- 4)
-
It's working. Thanks

- 5)
Welcome

**Comment by AlecAivazis** [comment]
Hey @amartyarej just wanted to give you a heads up that the zoom scroll is in fact in the latest version 🎉

**Comment by AlecAivazis** [comment]
@amartyarej I know it's been awhile since you reported this but I started looking to the issue with the `.sty` file and cannot file the line you are referencing - do you by chance have the specific line number?

**Comment by AlecAivazis** [comment]
@amartyarej I have fixed the issue in the `.sty` file as well as the issue preeventing labels from being seen in exported PNGs. I'm going to close this ticket - thanks again for reporting all of these issues and suggestions!
