### ISSUE TITLE
save a diagram as .svg or .eps and problem with .png

### ISSUE THREAD

**Issue by illuminates** [AlecAivazis/feynman#77]
Hello! First, thank you very much for Feynman diagrams online! It is very nice! 
A questions arose, however, 
1)	Is it possible save a diagram as .svg or .eps?
2)	When I save a diagram as .png then labels were losted.  Is there way to avoid that?

**Comment by AlecAivazis** [comment]
Hey @illuminates thanks for the kind words.

Saving a diagram as svg is definitely something that I have been meaning to get in but have just been unable to find the time. I'm also aware of the label bug and will work on getting a fix this weekend (i'll try to get saving as svg in too). 

Currently, there is no way to avoid the labels disappearing when saving as a PNG. The best alternative that I can suggest now is to take a screenshot of the diagram  which will leave it with a white background but that obviously is a not very satisfying response. Sorry I can't be more immediately helpful, i'll tag you when I have a fix for the labels.

**Comment by AlecAivazis** [comment]
Oh it just occured to me that since you asked for an SVG, you could pull it out of the the `<svg>` element in the app by opening up the element inspector and copying the HTML into a separate file, if this doesn't sound too scary, I can try to provide some screenshots to show you how to do it if you need them.

**Comment by illuminates** [comment]
Thanks for answering. If you could do some screenshots, I'd appreciate it.

**Comment by AlecAivazis** [comment]
Sorry for taking awhile to get you these. If you have a diagram showing on the app and open up the element inspector in chrome by clicking on `View > Developer > Javascript Console`

<img width="534" alt="screen shot 2017-05-07 at 10 25 09 am" src="https://cloud.githubusercontent.com/assets/916317/25783334/976ab1da-330f-11e7-8021-f4a7c8daf234.png">

There is an `Elements` tab to the left of `Console` in the pane that just hopefully showed up

<img width="292" alt="screen shot 2017-05-07 at 10 26 48 am" src="https://cloud.githubusercontent.com/assets/916317/25783344/bbcca38a-330f-11e7-84bc-0525a2397d1e.png">

When you click on it, you'll see the DOM (document object model) for the current state of the app. by the way, this will update as you change things in the UI. Anyway, There is an `<svg>` element under the `<main data-reactroot ...`. 

<img width="191" alt="screen shot 2017-05-07 at 10 29 49 am" src="https://cloud.githubusercontent.com/assets/916317/25783365/1fc93560-3310-11e7-9a1f-05952323aaac.png">

If you right click on it, and then click on `Edit as HTML` it should give you a box to copy the source of the svg diagram into. This wont look exactly how it does when exporting as a png since I do some massaging of the actual diagram you see. For example, you'll probably want to remove the elements under the `<g class="grid">`. Another thing you'll want to remove is the anchors which always come last in group of elements under the `<g class="diagram>`. Hope this helps. 

Btw, i spent a bunch of time this weekend working on fixing the issue with labels when exporting as PNG and hope to have something very very soon - stay tuned!

**Comment by AlecAivazis** [comment]
@illuminates I hope the above screenshots helped. In other news, you should now be seeing text exported in PNGs (they'll also be much higher quality)
