### ISSUE TITLE
Labels and text are not rendered

### ISSUE THREAD

**Issue by Bigben37** [AlecAivazis/feynman#88]
When I load the Drell-Yan pattern the labels are not rendered. However, they are set in the properties of the propagators and are also there in the LaTeX code.

The same issue for text. If I drag-and-drop text to the canvas it is not shown, however there is a corresponding line in the LaTeX code.

I'm having this issue with both Firefox and Chrome (both latest versions).

**Comment by AlecAivazis** [comment]
Hey @Bigben37 thanks for reporting this. I was able to verify that the labels are not showing up. Since this was for sure working a few weeks ago, I think it's likely a network issue with the latex rendering service. I'll take a look during my lunch break and hopefully have it fixed by the end of the day.

Sorry for any inconvinience this caused.

**Comment by AlecAivazis** [comment]
@Bigben37 I tried something before leaving this morning and it seems to have done the trick. Would you mind verifying that you can see the labels now?

**Comment by Bigben37** [comment]
Hi @AlecAivazis, it's working again for me, too.
Thanks for the quick fix!

**Comment by AlecAivazis** [comment]
Good to hear - thanks again for reporting it
